version: "3.8"

services:
  backend1:
    build:
      context: .
      dockerfile: Dockerfile
    image: my-backend
    container_name: backend1
    env_file:
      - ./.env
    ports:
      - "3001:3000"

  backend2:
    image: my-backend
    container_name: backend2
    env_file:
      - ./.env
    ports:
      - "3002:3000"
    depends_on:
      - backend1

  nginx:
    image: nginx:alpine
    container_name: nginx-proxy
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - backend1
      - backend2
